#pragma once

// MAP
#define COLS 5
#define ROWS 5

// PLAYER
#define MIN_HP_PLAYER 90
#define MAX_HP_PLAYER 110
#define MIN_STAMINA_PLAYER 90
#define MAX_STAMINA_PLAYER 110
#define MAX_POTIONS 3
#define MAX_AGILITY 3

// ENEMY
#define MIN_HP_ENEMY 60
#define MAX_HP_ENEMY 90
#define MIN_STAMINA_ENEMY 60
#define MAX_STAMINA_ENEMY 90

